INSERT INTO telegram_badges (id, name, emoji, description, category) VALUES
    ('method_dayan_7', '大雁功｜雁行入雲', '🪶', '累計練習「大雁功」7 天', 'METHOD_DAYS'),
    ('method_dayan_30', '大雁功｜雁翥沖虛', '🪽', '累計練習「大雁功」30 天', 'METHOD_DAYS'),
    ('method_dayan_100', '大雁功｜雁歸太和', '🌤️', '累計練習「大雁功」100 天', 'METHOD_DAYS'),
    ('method_wuqinxi_7', '五禽戲｜五行啟藏', '🕊️', '累計練習「五禽戲」7 天', 'METHOD_DAYS'),
    ('method_wuqinxi_30', '五禽戲｜五靈調炁', '🐾', '累計練習「五禽戲」30 天', 'METHOD_DAYS'),
    ('method_wuqinxi_100', '五禽戲｜五禽歸真', '🦚', '累計練習「五禽戲」100 天', 'METHOD_DAYS'),
    ('method_huichun_7', '回春功｜春芽復炁', '🌱', '累計練習「回春功」7 天', 'METHOD_DAYS'),
    ('method_huichun_30', '回春功｜春和養真', '🍃', '累計練習「回春功」30 天', 'METHOD_DAYS'),
    ('method_huichun_100', '回春功｜回春長青', '🌿', '累計練習「回春功」100 天', 'METHOD_DAYS'),
    ('method_guishou_7', '龜壽功｜龜息守一', '🐢', '累計練習「龜壽功」7 天', 'METHOD_DAYS'),
    ('method_guishou_30', '龜壽功｜龜鶴養元', '🪷', '累計練習「龜壽功」30 天', 'METHOD_DAYS'),
    ('method_guishou_100', '龜壽功｜壽炁綿長', '🏞️', '累計練習「龜壽功」100 天', 'METHOD_DAYS'),
    ('method_zhengyang_7', '正陽功｜朝陽啟炁', '🌅', '累計練習「正陽功」7 天', 'METHOD_DAYS'),
    ('method_zhengyang_30', '正陽功｜正陽養正', '☀️', '累計練習「正陽功」30 天', 'METHOD_DAYS'),
    ('method_zhengyang_100', '正陽功｜陽和充盈', '🌞', '累計練習「正陽功」100 天', 'METHOD_DAYS'),
    ('method_huanghai_7', '晃海功｜晃海聽潮', '🌊', '累計練習「神奇晃海功」7 天', 'METHOD_DAYS'),
    ('method_huanghai_30', '晃海功｜海定神凝', '🌌', '累計練習「神奇晃海功」30 天', 'METHOD_DAYS'),
    ('method_huanghai_100', '晃海功｜海天一炁', '🌐', '累計練習「神奇晃海功」100 天', 'METHOD_DAYS'),
    ('method_lotus_7', '蓮花養心法｜蓮心初照', '🪷', '累計練習「蓮花養心法」7 天', 'METHOD_DAYS'),
    ('method_lotus_30', '蓮花養心法｜蓮臺澄心', '💮', '累計練習「蓮花養心法」30 天', 'METHOD_DAYS'),
    ('method_lotus_100', '蓮花養心法｜蓮華見性', '🌺', '累計練習「蓮花養心法」100 天', 'METHOD_DAYS'),
    ('method_heqi_7', '和氣舒壓法｜和氣舒懷', '🍀', '累計練習「和氣舒壓法」7 天', 'METHOD_DAYS'),
    ('method_heqi_30', '和氣舒壓法｜和光同塵', '🌫️', '累計練習「和氣舒壓法」30 天', 'METHOD_DAYS'),
    ('method_heqi_100', '和氣舒壓法｜氣和神泰', '🌈', '累計練習「和氣舒壓法」100 天', 'METHOD_DAYS'),
    ('method_sanwo_7', '三窩功｜三窩聚炁', '🌀', '累計練習「三窩功」7 天', 'METHOD_DAYS'),
    ('method_sanwo_30', '三窩功｜三田歸元', '🫧', '累計練習「三窩功」30 天', 'METHOD_DAYS'),
    ('method_sanwo_100', '三窩功｜窩藏元和', '🪨', '累計練習「三窩功」100 天', 'METHOD_DAYS'),
    ('method_liuyin_7', '六音理臟法｜六音調藏', '🎵', '累計練習「六音理臟法」7 天', 'METHOD_DAYS'),
    ('method_liuyin_30', '六音理臟法｜六律和臟', '🎶', '累計練習「六音理臟法」30 天', 'METHOD_DAYS'),
    ('method_liuyin_100', '六音理臟法｜六炁周流', '🔔', '累計練習「六音理臟法」100 天', 'METHOD_DAYS'),
    ('method_jinggong_7', '靜功｜守靜入門', '🧘', '累計練習「靜功」7 天', 'METHOD_DAYS'),
    ('method_jinggong_30', '靜功｜澄心守一', '🪷', '累計練習「靜功」30 天', 'METHOD_DAYS'),
    ('method_jinggong_100', '靜功｜虛極靜篤', '🌌', '累計練習「靜功」100 天', 'METHOD_DAYS')
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    emoji = EXCLUDED.emoji,
    description = EXCLUDED.description,
    category = EXCLUDED.category;
